####
# Run the Quarkus application in JVM mode (fast-jar layout).
#
# Build the app first (from project root):
#   ./mvnw package -DskipTests
#
# Build image:
#   docker build -f src/main/docker/Dockerfile.jvm -t solar-csms .
#
# Or let Quarkus build it:
#   ./mvnw package -DskipTests -Dquarkus.container-image.build=true
####
FROM registry.access.redhat.com/ubi8/openjdk-21:1.20

ENV LANGUAGE='en_US:en'

COPY --chown=185 target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 target/quarkus-app/*.jar /deployments/
COPY --chown=185 target/quarkus-app/app/ /deployments/app/
COPY --chown=185 target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]
